
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CommonScheduleDetails': typeof import("../components/common/scheduleDetails.vue")['default']
    'CommonScheduleDialoge': typeof import("../components/common/scheduleDialoge.vue")['default']
    'CommonSpeakerCard': typeof import("../components/common/speakerCard.vue")['default']
    'CommonSpeakerSocialButton': typeof import("../components/common/speakerSocialButton.vue")['default']
    'CommonSponsorInfo': typeof import("../components/common/sponsorInfo.vue")['default']
    'CommonTeamCard': typeof import("../components/common/teamCard.vue")['default']
    'CoreAppDrawer': typeof import("../components/core/AppDrawer.vue")['default']
    'CoreAppFooter': typeof import("../components/core/AppFooter.vue")['default']
    'CoreAppToolbar': typeof import("../components/core/AppToolbar.vue")['default']
    'HomeCommunityContact': typeof import("../components/home/CommunityContact.vue")['default']
    'HomeExpectionSection': typeof import("../components/home/ExpectionSection.vue")['default']
    'HomeHeroSection': typeof import("../components/home/HeroSection.vue")['default']
    'HomeStats': typeof import("../components/home/HomeStats.vue")['default']
    'HomeSponsorsSection': typeof import("../components/home/SponsorsSection.vue")['default']
    'HomePastDevFest': typeof import("../components/home/pastDevFest.vue")['default']
    'HomeTechSection': typeof import("../components/home/techSection.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCommonScheduleDetails': typeof import("../components/common/scheduleDetails.vue")['default']
    'LazyCommonScheduleDialoge': typeof import("../components/common/scheduleDialoge.vue")['default']
    'LazyCommonSpeakerCard': typeof import("../components/common/speakerCard.vue")['default']
    'LazyCommonSpeakerSocialButton': typeof import("../components/common/speakerSocialButton.vue")['default']
    'LazyCommonSponsorInfo': typeof import("../components/common/sponsorInfo.vue")['default']
    'LazyCommonTeamCard': typeof import("../components/common/teamCard.vue")['default']
    'LazyCoreAppDrawer': typeof import("../components/core/AppDrawer.vue")['default']
    'LazyCoreAppFooter': typeof import("../components/core/AppFooter.vue")['default']
    'LazyCoreAppToolbar': typeof import("../components/core/AppToolbar.vue")['default']
    'LazyHomeCommunityContact': typeof import("../components/home/CommunityContact.vue")['default']
    'LazyHomeExpectionSection': typeof import("../components/home/ExpectionSection.vue")['default']
    'LazyHomeHeroSection': typeof import("../components/home/HeroSection.vue")['default']
    'LazyHomeStats': typeof import("../components/home/HomeStats.vue")['default']
    'LazyHomeSponsorsSection': typeof import("../components/home/SponsorsSection.vue")['default']
    'LazyHomePastDevFest': typeof import("../components/home/pastDevFest.vue")['default']
    'LazyHomeTechSection': typeof import("../components/home/techSection.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CommonScheduleDetails: typeof import("../components/common/scheduleDetails.vue")['default']
export const CommonScheduleDialoge: typeof import("../components/common/scheduleDialoge.vue")['default']
export const CommonSpeakerCard: typeof import("../components/common/speakerCard.vue")['default']
export const CommonSpeakerSocialButton: typeof import("../components/common/speakerSocialButton.vue")['default']
export const CommonSponsorInfo: typeof import("../components/common/sponsorInfo.vue")['default']
export const CommonTeamCard: typeof import("../components/common/teamCard.vue")['default']
export const CoreAppDrawer: typeof import("../components/core/AppDrawer.vue")['default']
export const CoreAppFooter: typeof import("../components/core/AppFooter.vue")['default']
export const CoreAppToolbar: typeof import("../components/core/AppToolbar.vue")['default']
export const HomeCommunityContact: typeof import("../components/home/CommunityContact.vue")['default']
export const HomeExpectionSection: typeof import("../components/home/ExpectionSection.vue")['default']
export const HomeHeroSection: typeof import("../components/home/HeroSection.vue")['default']
export const HomeStats: typeof import("../components/home/HomeStats.vue")['default']
export const HomeSponsorsSection: typeof import("../components/home/SponsorsSection.vue")['default']
export const HomePastDevFest: typeof import("../components/home/pastDevFest.vue")['default']
export const HomeTechSection: typeof import("../components/home/techSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCommonScheduleDetails: typeof import("../components/common/scheduleDetails.vue")['default']
export const LazyCommonScheduleDialoge: typeof import("../components/common/scheduleDialoge.vue")['default']
export const LazyCommonSpeakerCard: typeof import("../components/common/speakerCard.vue")['default']
export const LazyCommonSpeakerSocialButton: typeof import("../components/common/speakerSocialButton.vue")['default']
export const LazyCommonSponsorInfo: typeof import("../components/common/sponsorInfo.vue")['default']
export const LazyCommonTeamCard: typeof import("../components/common/teamCard.vue")['default']
export const LazyCoreAppDrawer: typeof import("../components/core/AppDrawer.vue")['default']
export const LazyCoreAppFooter: typeof import("../components/core/AppFooter.vue")['default']
export const LazyCoreAppToolbar: typeof import("../components/core/AppToolbar.vue")['default']
export const LazyHomeCommunityContact: typeof import("../components/home/CommunityContact.vue")['default']
export const LazyHomeExpectionSection: typeof import("../components/home/ExpectionSection.vue")['default']
export const LazyHomeHeroSection: typeof import("../components/home/HeroSection.vue")['default']
export const LazyHomeStats: typeof import("../components/home/HomeStats.vue")['default']
export const LazyHomeSponsorsSection: typeof import("../components/home/SponsorsSection.vue")['default']
export const LazyHomePastDevFest: typeof import("../components/home/pastDevFest.vue")['default']
export const LazyHomeTechSection: typeof import("../components/home/techSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
